xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    MF_TuleR_S10ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.005698744207620621
    MF_TuleR_S10FLOW:
      dims: []
      attrs: {}
      data: 20.187034606933594
    MF_TuleR_S10PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.022505439817905426
    MF_TuleR_S10SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.23274284601211548
    MF_TuleR_S10STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.1637156009674072
    MF_TuleR_S10SWE-OBSERVED:
      dims: []
      attrs: {}
      data: 0.10620547086000443
    MF_TuleR_S10TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 12.778291702270508
    MF_TuleR_S20ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.004515709355473518
    MF_TuleR_S20FLOW:
      dims: []
      attrs: {}
      data: 186.93019104003906
    MF_TuleR_S20PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.032956864684820175
    MF_TuleR_S20SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.22228725254535675
    MF_TuleR_S20STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.1114333868026733
    MF_TuleR_S20SWE-OBSERVED:
      dims: []
      attrs: {}
      data: 5.269899368286133
    MF_TuleR_S20TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 12.275967597961426
    NF_TuleR_S10ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.005512613337486982
    NF_TuleR_S10FLOW:
      dims: []
      attrs: {}
      data: 93.15316009521484
    NF_TuleR_S10PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.025193633511662483
    NF_TuleR_S10SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.22674602270126343
    NF_TuleR_S10STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.1337288618087769
    NF_TuleR_S10SWE-OBSERVED:
      dims: []
      attrs: {}
      data: 1.359254240989685
    NF_TuleR_S10TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 12.494394302368164
    ReservoirInflowFLOW:
      dims: []
      attrs: {}
      data: 376.7563171386719
    ReservoirInflowFLOW-OBSERVED:
      dims: []
      attrs: {}
      data: 445.7032775878906
    SF_TuleR_S10ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.005439335480332375
    SF_TuleR_S10FLOW:
      dims: []
      attrs: {}
      data: 103.2445068359375
    SF_TuleR_S10PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.024029064923524857
    SF_TuleR_S10SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.22621338069438934
    SF_TuleR_S10STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.1310646533966064
    SF_TuleR_S10SWE-OBSERVED:
      dims: []
      attrs: {}
      data: 1.0414878129959106
    SF_TuleR_S10TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 12.688777923583984
    TuleR_S10ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.007126498501747847
    TuleR_S10FLOW:
      dims: []
      attrs: {}
      data: 6.273548603057861
    TuleR_S10PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.013572927564382553
    TuleR_S10SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.2091299295425415
    TuleR_S10STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.0456477403640747
    TuleR_S10TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 12.930240631103516
    TuleR_S20ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.006559826899319887
    TuleR_S20FLOW:
      dims: []
      attrs: {}
      data: 15.585413932800293
    TuleR_S20PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.017456553876399994
    TuleR_S20SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.22572754323482513
    TuleR_S20STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.1286375522613525
    TuleR_S20SWE-OBSERVED:
      dims: []
      attrs: {}
      data: 0.01376034040004015
    TuleR_S20TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 12.72938060760498
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    MF_TuleR_S10ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.010421489365398884
    MF_TuleR_S10FLOW:
      dims: []
      attrs: {}
      data: 9.066192626953125
    MF_TuleR_S10PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.008416694588959217
    MF_TuleR_S10SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.2960573732852936
    MF_TuleR_S10STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.4802862405776978
    MF_TuleR_S10SWE-OBSERVED:
      dims: []
      attrs: {}
      data: 0.028561078011989594
    MF_TuleR_S10TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 55.43836975097656
    MF_TuleR_S20ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.007275283802300692
    MF_TuleR_S20FLOW:
      dims: []
      attrs: {}
      data: 87.60897827148438
    MF_TuleR_S20PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.012578173540532589
    MF_TuleR_S20SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.3722079396247864
    MF_TuleR_S20STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.8610398769378662
    MF_TuleR_S20SWE-OBSERVED:
      dims: []
      attrs: {}
      data: 3.20131778717041
    MF_TuleR_S20TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 46.42398452758789
    NF_TuleR_S10ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.010048949159681797
    NF_TuleR_S10FLOW:
      dims: []
      attrs: {}
      data: 51.729820251464844
    NF_TuleR_S10PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.009472344070672989
    NF_TuleR_S10SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.30942121148109436
    NF_TuleR_S10STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.547105312347412
    NF_TuleR_S10SWE-OBSERVED:
      dims: []
      attrs: {}
      data: 0.8075203895568848
    NF_TuleR_S10TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 54.324729919433594
    ReservoirInflowFLOW:
      dims: []
      attrs: {}
      data: 212.1984100341797
    ReservoirInflowFLOW-OBSERVED:
      dims: []
      attrs: {}
      data: 232.49371337890625
    SF_TuleR_S10ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.00969623401761055
    SF_TuleR_S10FLOW:
      dims: []
      attrs: {}
      data: 54.48155975341797
    SF_TuleR_S10PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.009126320481300354
    SF_TuleR_S10SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.309383749961853
    SF_TuleR_S10STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.5469188690185547
    SF_TuleR_S10SWE-OBSERVED:
      dims: []
      attrs: {}
      data: 0.5957552194595337
    SF_TuleR_S10TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 53.33928680419922
    TuleR_S10ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.013610146939754486
    TuleR_S10FLOW:
      dims: []
      attrs: {}
      data: 2.430494546890259
    TuleR_S10PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.004604723304510117
    TuleR_S10SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.20878347754478455
    TuleR_S10STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.0439176559448242
    TuleR_S10TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 63.30345153808594
    TuleR_S20ET-POTENTIAL:
      dims: []
      attrs: {}
      data: 0.012464889325201511
    TuleR_S20FLOW:
      dims: []
      attrs: {}
      data: 6.880319595336914
    TuleR_S20PRECIP-INC:
      dims: []
      attrs: {}
      data: 0.006271521560847759
    TuleR_S20SATURATION FRACTION:
      dims: []
      attrs: {}
      data: 0.2506415843963623
    TuleR_S20STORAGE-SOIL:
      dims: []
      attrs: {}
      data: 1.253207802772522
    TuleR_S20SWE-OBSERVED:
      dims: []
      attrs: {}
      data: 0.002247343072667718
    TuleR_S20TEMPERATURE-AIR:
      dims: []
      attrs: {}
      data: 60.65980529785156
